language: node_js
node_js: stable
script: ./node_modules/.bin/nyc npm test
cache:
  directories:
  - $HOME/.npm
  - $HOME/.yarn-cache
after_success: ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls